### ISSUE TITLE
Ensure all functions/classes have proper jsDocs

### ISSUE THREAD

**Issue by kadler** [IBM/nodejs-itoolkit#100]
Need to update jsdocs for :

- [x] Connection.js

- [x] ProgramCall.js

- [x] CommandCall.js

- [x] Deprecated.js

**Comment by abmusse** [comment]
Need to update jsdocs for :

- [ ] Connection.js

- [ ] ProgramCall.js

- [ ] CommandCall.js

- [ ] Deprecated.js
