### ISSUE TITLE
Extraneous asterisk in issue template

### ISSUE THREAD

**Issue by kadler** [IBM/nodejs-itoolkit#112]
**Describe the bug**
There's an extra asterisk in the issue template after "XMLSERVICE version"

**To Reproduce**
1. Open a new bug report

**Expected behavior**
The asterisk should not be there.

**Screenshots**

![image](https://user-images.githubusercontent.com/7004340/74547287-7e496900-4f11-11ea-819a-3b1a2ca7ab73.png)

**Comment by kadler** [comment]
The numbered list in the steps to reproduce also vary whether they have a trailing blank or not. I would suggest to have the trailing blank so it's ready to fill in by the user.

**Comment by abmusse** [comment]
Thanks I will fix this up
