### ISSUE TITLE
How to make job MSGW?

### ISSUE THREAD

**Issue by Benzhucn** [IBM/nodejs-itoolkit#114]
We are call nodejs programs by AS400 job, so when the nodejs programs running, there is a as400 job in the subsystem. The problem is that, when the nodejs program got error or have issue, we can't know if not monitor the job status. I tried to do it by sending message of CL command and make the job in MSGW, but failed. How can I do it?

**Comment by kadler** [comment]
I'm not sure I follow what the question is (or whether it's really an itoolkit issue at all).

Can you give an example of what you're trying to accomplish?

**Comment by Benzhucn** [comment]
> I'm not sure I follow what the question is (or whether it's really an itoolkit issue at all).
> 
> Can you give an example of what you're trying to accomplish?

Our NODEJS job is submited by command SBMJOB, and in the job will run QSH /nodejsprogram. So, the nodejs jobs run in the dedicate subsystem, and then we can monitor it. Now, in some case, we would like to make the nodejs job in the subsystem to in MSGW status.

**Comment by kadler** [comment]
Why do you want the job to go in to MSGW?

**Comment by patrickhrastnik** [comment]
I hope I get the question correctly: You want to submit a job to run a node.js application, and in case it crashes, you‘d like to get a MSGW status / a QSYSOPR message - am I right?
That‘s the behavior I wanted to reach back when we started to use our node.js runtime in production mode.
I developed a CL script that goes about as follows (it‘s been a while, so please forgive me if I miss something important):
- loop to re-play the server start script if necessary, with an end condition variable that‘s set manually
- run QSH command with a bash script to start the server application
- check if current job got a signal to end the process
  - if so, leave the loop
  - if not, send a message to QSYSOPR with a request for a reply, in our case R to retry and I to ignore the error and end job execution

That came in hand recently, suddenly our application crashed, and we were able to restart it immediately via the QSYSOPR message.
Anyhow, I‘m rather looking for a solution with multithreading and a process manager runtime by now. The script was a good start for us, but one single application thread with just four worker threads is just not enough for our expected workload.

**Comment by patrickhrastnik** [comment]
Here's our script (I already adopted it to not contain specifics of our runtime, so you might be able to copy-paste it)

```CLLE
pgm
   dcl var(&restart) type(*lgl)
   dcl var(&jobend) type(*char) len(20)
   dcl var(&reply) type(*char) len(20)

   chgvar &jobend ' '
   chgvar &reply ' '

   addenvvar envvar(QIBM_MULTI_THREADED) value(Y)
   monmsg cpf0000

   chgvar &restart '1'
   dowhile cond(&restart *eq '1')
     chgvar &restart '0'

     qsh cmd('bash /node/start.sh')

     rtvjoba endsts(&jobend)
     if cond(&jobend *ne '1') then(do)
       sndusrmsg msg('(I R) NodeJS was ended abnormally. +
        Reply with R to restart the application.') +
         values(I R) dft(R) msgtype(*inq) tomsgq(*sysopr) +
         msgrpy(&reply)
       if cond(&reply *eq R) then(do)
         chgvar &restart '1'
       enddo
     enddo
   enddo
endpgm
```
