### ISSUE TITLE
build: Add xml2js as a dependency

### ISSUE THREAD

**Issue by abmusse** [IBM/nodejs-itoolkit#125]
In #99 we want to deprecate `xmlToJson` in out code code (Toolkit.js), tests, docs, and examples in favor of `xml2js`.

To do so we would need to add `xml2js` a dependency in our `package.json`.

Doing so will also make `xml2js` available for users.

**Comment by ThePrez** [comment]
Is `xml2js` really required? It seems our examples and doc would show to use `xml2js` but this package doesn't explicitly need it, except for tests

**Comment by ThePrez** [comment]
Ahh, looks like we do require it here: https://github.com/IBM/nodejs-itoolkit/commit/071c5460839d729a2a3d33b51c81d52ac681bd28

**Comment by abmusse** [comment]
> Ahh, looks like we do require it here: [071c546](https://github.com/IBM/nodejs-itoolkit/commit/071c5460839d729a2a3d33b51c81d52ac681bd28)
> 
> Perhaps this PR should be merged with #122

Sounds good, That is what I had initially.

I separated this out because I wanted to open additional PRs that use xml2js with the tests.

**Comment by abmusse** [comment]
Also I wanted to break down #122 into several smaller PRs because the diff is really large.
