### ISSUE TITLE
Add idb-connector to Dependencies in Package.json

### ISSUE THREAD

**Issue by abmusse** [IBM/nodejs-itoolkit#13]
**[Original report](https://bitbucket.org/litmis/nodejs-itoolkit/issue/13) by me.**

----------------------------------------

Package.json Should list idb-connector as a dependancy because it is required on line 50 of istroedp.js.
```
#!js
  db = require('idb-connector');
```
That way if someone npm installs itoolkit without already having idb-connector it will work.

**Comment by kadler** [comment]
Seems like this would be sufficient: https://docs.npmjs.com/files/package.json#optionaldependencies

**Comment by abmusse** [comment]
> Seems like this would be sufficient: https://docs.npmjs.com/files/package.json#optionaldependencies

So on non ibm i systems itoolkit will still install properly even though idb-connector wont install.

**Comment by abmusse** [comment]
Moved `idb-connector` to optional deps in 85a2e54f41d6a0e172053fa3c14e9d5863330da3
