### ISSUE TITLE
It can't run command of SNDPGMMSG or SNDUSRMSG

### ISSUE THREAD

**Issue by Benzhucn** [IBM/nodejs-itoolkit#135]
Hi, 
  We would like to run the command SNDPGMMSG or SNDUSRMSG to send message with message id, but failed. Only can send message by command SNDMSG, but it can't with message id.
 Could this is a bug or any speical thing need to setup when call command SNDPGMMSG?

Best Regards,
Ben

* **Node.js version**:
* **itoolkit version**:
* **IBM i version**:
* **XMLSERVICE version**:

**Describe the bug**

**To Reproduce**
1. 
2. 
3. 
4. 
5. 

**Expected behavior**

**Screenshots**

**Comment by abmusse** [comment]
Hello :wave: @Benzhucn 

Please fill out this section:

```
Node.js version:
itoolkit version:
IBM i version:
XMLSERVICE version
```

Also provide steps to reproduce the error. 

```
Steps to reproduce the behavior:
1.
2.
3.
```

This will be the code snippet you have tried and the error you have encountered.

Providing the above information helps us help you.

Thanks!
