### ISSUE TITLE
When can this package go to at least 1.x?

### ISSUE THREAD

**Issue by abmusse** [IBM/nodejs-itoolkit#14]
**[Original report](https://bitbucket.org/litmis/nodejs-itoolkit/issue/14) by Jesse G (Bitbucket: [ThePrez](https://bitbucket.org/ThePrez), GitHub: [ThePrez](https://github.com/ThePrez)).**

----------------------------------------

Seems it has been burnt in enough that would justify a major version number > 0.

**Comment by kadler** [comment]
See the Version 1.0 milestone for tracking https://github.com/IBM/nodejs-itoolkit/milestone/1

**Comment by markdirish** [comment]
I don't know if this is easier to track than 'milestones', but I also made a 'project' : [https://github.com/IBM/nodejs-itoolkit/projects/1](https://github.com/IBM/nodejs-itoolkit/projects/1)
