### ISSUE TITLE
Setup PR testing with unit tests

### ISSUE THREAD

**Issue by abmusse** [IBM/nodejs-itoolkit#144]
We should run our  [unit tests](https://github.com/IBM/nodejs-itoolkit/tree/master/test/unit)  for any PR intended for the master branch.

**Comment by kadler** [comment]
FYI the default github workflow for npm packages is to use `npm ci` and apparently it requires a package-lock.json to work. I also found this: https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5

Sounds like we should commit our package-lock.json before we can really use CI.
