### ISSUE TITLE
Question: Do we need the files in test/rpg ?

### ISSUE THREAD

**Issue by abmusse** [IBM/nodejs-itoolkit#154]
Within our test files we have some rpg files:

![image](https://user-images.githubusercontent.com/33973272/76661684-130fa880-654a-11ea-9808-956a8aa76f59.png)

These are provided by xmlservice when its built with tests.

I do not think we should be tracking these files in this repo.

I would like to remove the `test/rpg` directory.

@kadler @dmabupt 

Do we need these files?

**Comment by kadler** [comment]
Nope, I don't think so. Those are XMLSERVICE files.
