### ISSUE TITLE
How to close itoolkit connection?

### ISSUE THREAD

**Issue by abmusse** [IBM/nodejs-itoolkit#17]
**[Original report](https://bitbucket.org/litmis/nodejs-itoolkit/issue/17) by Jesse G (Bitbucket: [ThePrez](https://bitbucket.org/ThePrez), GitHub: [ThePrez](https://github.com/ThePrez)).**

----------------------------------------

If I am using the iDb2Call transport, how does the connection get closed?

**Comment by abmusse** [comment]
After reviewing the code again I think we should call 
- `conn.close()` - calls SQLFreeConnect 
- `stmt.close()` - calls SQLFreeStmt 

To ensure the connection and statement are freed properly. 

Instead of using JavaScript `delete` keyword which is meant to remove properties from an object

**Comment by kadler** [comment]
Does a `conn.close()` not close all of its statements?

**Comment by abmusse** [comment]
> Does a conn.close() not close all of its statements?

`conn.close()` makes a call to [SQLFreeConnect](https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_73/cli/rzadpfnfconn.htm) which in the doc states:

`
SQLFreeConnect() invalidates and frees the connection handle. All DB2® for i CLI resources associated with the connection handle are freed.`

Does this imply that the statements attached to the connection will also be freed?

**Comment by kadler** [comment]
I don't think IBM i CLI frees any statement handles. The database resources associated with them may be implicitly freed, but the statements are still assigned and "valid". I'd suggest having the connection keep a reference to it's statement objects and closing them all in `conn.close`.

**Comment by abmusse** [comment]
That makes sense would need to implement this within [idb-connector](https://github.com/IBM/nodejs-idb-connector/).

I can open an issue with the suggestion over at that repo for further discussion.

For now I suppose we should explicitly close the statement and connection with 

`stmt.close() - calls SQLFreeStmt`
`conn.disconn() - calls SQLDisconnect`
`conn.close() - calls SQLFreeConnect`

**Comment by abmusse** [comment]
PR https://github.com/IBM/nodejs-itoolkit/pull/42 reworks idb transport to clean up properly.

**Comment by abmusse** [comment]
Closing PR #42 adds cleanup for Connections.
