### ISSUE TITLE
QSH Command tests fail with XMLSERVICE < 1.9.8

### ISSUE THREAD

**Issue by kadler** [IBM/nodejs-itoolkit#193]
the `<qsh>` tag was not added until XMLSERVICE 1.9.8: http://yips.idevcloud.com/wiki/index.php/XMLService/XMLSERVICEQuick#qsh

We need a before check that XMLSERVICE is at 1.9.8 or higher or we need to ignore the failure when the error shows that XMLSERVICE is too old.

**Comment by abmusse** [comment]
Whats a consistent way we can check xmlservice version across the different transports?

**Comment by kadler** [comment]
XMSERVICE doesn't have a good way to get the license. A `<version>` tag is returned when error=on and an error occurs. Its also returned somehow when the `*license` control flag is set.

Another way would be to do a QSH call to /qsys.lib/qxmlserv.lib/xmlver.pgm and grab the output.

**Comment by kadler** [comment]
I suppose the test could set error=on and then check the version given back. Of course, this would require access to a XMLSERVICE 1.9.7 or earlier install in order to validate that the check is correct.

**Comment by abmusse** [comment]
Calling and grabbing the output from `/qsys.lib/qxmlserv.lib/xmlver.pgm` might be the best option

We can use system utility for the ssh transport and [QSYS2.QCMDEXC](https://www.ibm.com/support/pages/qsys2qcmdexc) for odbc and idb transport.

Here is example output from the system command

```
$ system "STRQSH CMD('/qsys.lib/qxmlserv.lib/xmlver.pgm')"
XML Toolkit 2.0.2-devQSH0005: Command ended normally with exit status 0.
```
