### ISSUE TITLE
Callback function should receive error parameter

### ISSUE THREAD

**Issue by abmusse** [IBM/nodejs-itoolkit#2]
**[Original report](https://bitbucket.org/litmis/nodejs-itoolkit/issue/2) by Aaron Bartell (Bitbucket: [aaronbartell](https://bitbucket.org/aaronbartell), GitHub: [aaronbartell](https://github.com/aaronbartell)).**

----------------------------------------

Currently the iToolkit callback function only operates on a [single result parameter](http://ibm.co/2kV7oA8) and doesn't also include an error parameter.  Errors could result from the DB2 connection.

Would be good to add this so errors can be conveyed.

**Comment by abmusse** [comment]
PR https://github.com/IBM/nodejs-itoolkit/pull/42 allows `Connection.run()` to invoke users callback with error first and xml output second, 

This can be configured by setting `returnError: false` within Connection constructor.

**Comment by kadler** [comment]
@abmusse To be clear, the default is to return errors (`returnError: true`) when using the new "single object" constructor, but to not return errors when using the old style with multiple parameters, correct?

**Comment by abmusse** [comment]
@kadler Correct when using the old style `(db, username, password, [options])` `returnError` is set to false.

**Comment by abmusse** [comment]
Closing `v1.0.0` will include error first callback within `connection.run()` by default when using new  "single object" constructor.
