### ISSUE TITLE
Switch tests from arrow functions

### ISSUE THREAD

**Issue by kadler** [IBM/nodejs-itoolkit#200]
Mocha recommends against arrow functions as it prevents access to the Mocha context: https://mochajs.org/#arrow-functions

This prevents us from setting timeouts (#198) or slow time (#199).

**Comment by abmusse** [comment]
I think part of the reason we used arrow functions is because the linter prefers arrow functions.

**Comment by kadler** [comment]
Yes, I did get bajillions of linter errors when I tried using regular functions. However, eslint should understand that mocha had different linting requirements. There's a plugin for mocha eslint rules: https://www.npmjs.com/package/eslint-plugin-mocha and we set `/* eslint-env mocha */` in the tests. I haven't gotten that to work fully yet, though. Something to look at in the future.
