### ISSUE TITLE
Outdated/Conflicting Documentation

### ISSUE THREAD

**Issue by I3uckwheat** [IBM/nodejs-itoolkit#22]
The link for the api reference documentation directs one to: [here](https://www.ibm.com/developerworks/community/wikis/home?lang=en#!/wiki/IBM%20i%20Technology%20Updates/page/Toolkit%20for%20i%20APIs)

This is however inconsistent with the examples listed in the README.md

![image](https://user-images.githubusercontent.com/4411701/51713698-7b26c680-1ff8-11e9-98dd-23a15299f2c1.png)

![image](https://user-images.githubusercontent.com/4411701/51713713-8548c500-1ff8-11e9-981f-8e53870ab6e9.png)

**Comment by I3uckwheat** [comment]
related to: #10

**Comment by kadler** [comment]
The developerWorks docs are out of date. Those docs should be migrated in to this repo and removed from developerWorks (just point a URL back to wherever they land in here).

**Comment by abmusse** [comment]
> The developerWorks docs are out of date. Those docs should be migrated in to this repo and removed from developerWorks (just point a URL back to wherever they land in here).

Agreed docs should be migrated from developer works to docs/README.md file

We should  reopen #10

**Comment by abmusse** [comment]
Some quick thoughts on what to update from developer works:

 - [ ] use 'itoolkit' for requires rather than OPS path
-  [ ] use es6 syntax ex: replace `var` with `let` and `const`

@I3uckwheat @kadler 

Any other thoughts on what to update from developer works docs?

**Comment by ThePrez** [comment]
Maybe we should keep the OPS path up for another 3 months until OPS Node.js is completely dead (doc as an alternative, non-recommended path), but make the primary path npm itoolkit (but then we need to circle back in a few months and clean it up, which we should probably do for all of the OPS content anyway)

**Comment by I3uckwheat** [comment]
I am happy to help with updating the documentation. 

Some concerns/problems I have run into:

- npm installation isn't mentioned (I believe it's the OPS Node.js @ThePrez mentioned)
- nesting is missing on some of the example XML snippets
- non-explicit variable names can get confusing. e.g. `xt`
- Nothing stating the params put in can also be returned, and the usage of `returnParam`
- in the iPgm docs, it doesn't state you have to pass in an empty value to a parameter to get a return value, this has caused much confusion on my part.
- How to setup and use the itoolkit and not create a new instance each time it's used.

**Comment by abmusse** [comment]
Closing after merging PR #58
