### ISSUE TITLE
Refactor Code for 1.0

### ISSUE THREAD

**Issue by markdirish** [IBM/nodejs-itoolkit#23]
This entire repository needs a ~little~ lot of TLC. For instance, it seems to have been written with no deference to DRY principles. For example, `lib/idataq.js` has a class with 3 functions, `sendToDataQueue`, `receiveFromDataQueue`, and `clearDataQueue`. 90% of the code in these functions is the same, the only difference is the iPgm parameters that are added at the beginning of functions. The rest of the code is more like... looping and waiting for the results to come back, and I'm not even sure that code is written all that great.

While I'm linting (#21), I'm going to get familiar with the program and then I'll propose what we should do to abstract a lot of this out into a single function, then pass the parameters that need to be sent to the pgm.

**Comment by I3uckwheat** [comment]
Should moving to es6 syntax be considered as well? As well as more functional style programming?

**Comment by abmusse** [comment]
Resolved by PR #33
