### ISSUE TITLE
Data queue memory leak itoolkit 0.1.6 + idb-connector

### ISSUE THREAD

**Issue by bmcq92** [IBM/nodejs-itoolkit#230]
We're having issues in production similar to [this issue](https://github.com/IBM/nodejs-idb-connector/issues/90) raised in idb-connector a while ago.

We're seeing the temporary storage use on the node job increase rather fast when reading and writing to data queues. This doesn't happen when using the REST transport so I thought this may be an issue with idb-connector. On further testing, I've found the issue doesn't seem to occur with the newer alpha1 version of itoolkit in npm repos using the Toolkit class to read/write data queues so decided to raise it here instead.

Are you still supporting issues with the older version of itoolkit? If not, are there plans to implement reading/writing **keyed** data queues in the newer version soon™ ([it looks like Toolkit dataqueue stuff is being canned](https://github.com/IBM/nodejs-itoolkit/issues/97))?

Thanks.

**Comment by kadler** [comment]
There are some big overhauls going on, though we plan to be 99% compatible with v0.1 in v1.0. Those APIs will be deprecated once #151 lands, but they will stick around for the whole v1 lifetime. Please open a feature request if you want keyed data queue support.

As to this issue, looks like were not closing the statement object we create. Compare [v1.0.6](https://github.com/IBM/nodejs-itoolkit/blob/v0.1.6/lib/istoredp.js#L87-L89) with [master](https://github.com/IBM/nodejs-itoolkit/blob/master/lib/transports/idbTransport.js#L63-L65)

**Comment by ThePrez** [comment]
Also of note, the new [DATA_QUEUE_* SQL services](http://ibm.biz/DB2foriServices) have support for keyed data queues and allow you to read/write.

**Comment by bmcq92** [comment]
Thanks for the quick response. Tested your changes above and it looks much better now. Job temporary storage use is down at 50MB after 1000 send and receives rather than in the 300's and increasing.

Will raise a feature request for keyed data queues tomorrow.
