### ISSUE TITLE
fixup TODOs in Deprecated.js

### ISSUE THREAD

**Issue by abmusse** [IBM/nodejs-itoolkit#238]
There a few lingering TODOs in `Deprecated.js`.

For example there are commented duplicate keys for output objects:

```js
...
            // Reserved: data[27]._, // TODO: duplicate key
...
```

I'm not sure there is much use returning the Reserved keys anyway because there are always `undefined`. We should probably remove these.

The other TODO is with [work.getSysValue](https://github.com/IBM/nodejs-itoolkit/blob/master/lib/Deprecated.js#L2770) I noticed there is a silent return here when the system value is not found in the [sysvalArray](https://github.com/IBM/nodejs-itoolkit/blob/master/lib/Deprecated.js#L2731).

**Comment by kadler** [comment]
You can't remove reserved fields, because they are needed to keep the layout correct in a packed data structure

You can remove the name from them, though

**Comment by abmusse** [comment]
OK what I meant was removing it from the [object](https://github.com/IBM/nodejs-itoolkit/blob/master/lib/Deprecated.js#L770) that gets returned to the user.

**Comment by kadler** [comment]
Oh right, these are the higher-level wrappers. Yep, makes sense to not return the useless data to the user in that case.
