### ISSUE TITLE
Core dump from calling Connection constructor with no args

### ISSUE THREAD

**Issue by ThePrez** [IBM/nodejs-itoolkit#275]
* **Node.js version**: 8.17.0
* **itoolkit version**: 1.0.0-alpha.1
* **IBM i version**: IBM i 7.3
* **XMLSERVICE version**: unknown

**Describe the bug**
the following code causes a core dump
```
const { Connection, CommandCall } = require('itoolkit');
const connection = new Connection();
```
**To Reproduce**
run the above code

**Expected behavior**
Either a decent error should be thrown, or a no-args invocation should behave the same as:
```javascript
const connection = new Connection({
  transport: 'idb',
  transportOptions: { database: '*LOCAL' }
});
```

**Comment by kadler** [comment]
>Either a decent error should be thrown, or a no-args invocation should behave the same as ...

Part of the goal of v1.0 was moving away from implicitly doing things, so I would recommend doing the former.

**Comment by abmusse** [comment]
Weird I would expect the following error to be thrown `Error: options must be an object` see https://github.com/IBM/nodejs-itoolkit/blob/master/lib/Connection.js#L99.

**Comment by abmusse** [comment]
Using the latest changes in master I'm unable to reproduce the bug

1. npm install IBM/nodejs-itoolkit#master

2. make a new file test.js with the following contents 
```js
const { Connection, CommandCall } = require('itoolkit');
const connection = new Connection();
```

3. Run `node test.js`:

**Output**:

```
$ node test.js 
/../node_modules/itoolkit/lib/Connection.js:99
      throw new Error('options must be an object');
      ^

Error: options must be an object
    at new Connection (/../node_modules/itoolkit/lib/Connection.js:99:13)

```

**Comment by ThePrez** [comment]
This initial bug report is wrong. The core dump doesn't happen until I use the object. Here's the full code

```javascript
const { Connection, CommandCall } = require('itoolkit');
const { parseString } = require('xml2js');

const connection = new Connection();

const command = new CommandCall({ type: 'sh', command: 'system -i DSPSYSSTS' });

connection.add(command);

connection.run((error, xmlOutput) => {
  if (error) {
    throw error;
  }
  parseString(xmlOutput, (parseError, result) => {
    if (parseError) {
      throw parseError;
    }
    let backslashn = /\\n/g;
    console.log(JSON.stringify(result.myscript.sh[0]._).replace(backslashn,'\n'));
  });
});
```



Is it just that we're plain not calling the right constructor?
Perhaps on this line:  https://github.com/IBM/nodejs-itoolkit/blob/d5e71c159319574a937ee415df4c636d7f347ba7/lib/Connection.js#L93 
```javascript
     constructor(options) {
```
should instead be
```javascript
     constructor(options = undefined) {
```

**Comment by ThePrez** [comment]
Nope, not that ^^^ .. 
Looks like the latest `alpha` on npm doesn't match GitHub master

**Comment by kadler** [comment]
Yeah, the alpha was released last year.

**Comment by kadler** [comment]
Also, parameters not passed will automatically be `undefined`, so the suggestion above while well meaning, will not make any difference.

**Comment by kadler** [comment]
@abmusse Can you publish an "rc1" tag?

**Comment by abmusse** [comment]
Do you mean an [npm tag](https://docs.npmjs.com/cli/dist-tag) so that I will be installable with `npm install itoolkit@rc1` ?

**Comment by kadler** [comment]
Yep, exactly.

**Comment by ThePrez** [comment]
After running `npm install itoolkit@rc1` the problem appears solved

```pascal
-bash-4.4$ node index
/home/JGORZINS/cl/node_modules/itoolkit/lib/Connection.js:99
      throw new Error('options must be an object');
      ^

Error: options must be an object
    at new Connection (/home/JGORZINS/cl/node_modules/itoolkit/lib/Connection.js:99:13)
    at Object.<anonymous> (/home/JGORZINS/cl/index.js:4:20)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
```

So, it's just a matter in the latest-published "alpha" but this is fixed in master. 

Thanks!
