### ISSUE TITLE
Exclude docs directory during npm publish

### ISSUE THREAD

**Issue by abmusse** [IBM/nodejs-itoolkit#277]
While releasing `v1.0.0-rc.1` I noticed that all the `.rst` files in the docs directory were being packaged.

![image](https://user-images.githubusercontent.com/33973272/80844675-dc125680-8bcc-11ea-8187-a1f37bde1a59.png)

I don't think we should be package these when publishing.

We can ignore these by adding `docs/` to our [.npmignore](https://github.com/IBM/nodejs-itoolkit/blob/master/.npmignore).

**Comment by kadler** [comment]
Should we get this in the v1?

**Comment by abmusse** [comment]
Yes I will get this in for v1.0.0.
