### ISSUE TITLE
itoolkit issues

### ISSUE THREAD

**Issue by Desibabe** [IBM/nodejs-itoolkit#285]
* **Node.js version**:  12.16.2
* **itoolkit version**: 1.0.0
* **IBM i version**: 7.2
* **XMLSERVICE version**: 

I am on ISeries V7.2, installed latest itoolkit from this page when I run sample js file shown on this page I get a following error message:

 Error: xmlserivce-cli exited abnormally with code: 1                                                            
     at Channel.<anonymous> (/home/xxxxx/myApp/node_modules/itoolkit/lib/transports/sshTransport.js:79:32)    
     at Channel.emit (events.js:310:20)                                                                          
     at SSH2Stream.<anonymous> (/home/xxxx/myApp/node_modules/ssh2/lib/Channel.js:210:14)                    
     at SSH2Stream.emit (events.js:310:20)                                                                       
     at parse_CHANNEL_REQUEST (/home/xxx/myApp/node_modules/ssh2-streams/lib/ssh.js:4467:8)                 
     at parsePacket (/home/xxxx/myApp/node_modules/ssh2-streams/lib/ssh.js:3768:12)                          
     at SSH2Stream._transform (/home/xxxx/myApp/node_modules/ssh2-streams/lib/ssh.js:701:13)                 
     at SSH2Stream.Transform._read (_stream_transform.js:191:10)                                                 
     at SSH2Stream._read (/home/xxxx/myApp/node_modules/ssh2-streams/lib/ssh.js:253:15)                      
     at SSH2Stream.Transform._write (_stream_transform.js:179:12)                                                
 $                                                                                                               

What could have gone wrong here?

Also, xmlserive is misspelled, should be xmlservice.

**Comment by abmusse** [comment]
Hello  :wave: @Desibabe

Are you refering to the example in the main README?

```js
const { Connection, CommandCall } = require('itoolkit');
const { parseString } = require('xml2js');

const connection = new Connection({
  transport: 'ssh',
  transportOptions: { host: 'myhost', username: 'myuser', password: 'mypassword' },
});

const command = new CommandCall({ type: 'cl', command: 'RTVJOBA USRLIBL(?) SYSLIBL(?)' });

connection.add(command);

connection.run((error, xmlOutput) => {
  if (error) {
    throw error;
  }
  parseString(xmlOutput, (parseError, result) => {
    if (parseError) {
      throw parseError;
    }
    console.log(JSON.stringify(result));
  });
});
```

I found that above example was missing braces `  });` at the end. I've opened #286 to resolve that problem. 

As for `Error: xmlservice-cli exited abnormally with code: 1` issue you described above. First off can you confirm that you have `itoolkit-utils` rpm package installed?

```
$ yum list installed itoolkit-utils
Installed Packages
itoolkit-utils.ppc                                       1.0.0-1    
```

itoolkit-utils provides `xmlservice-cli` binary that is required for the [ssh transport](https://nodejs-itoolkit.readthedocs.io/en/latest/Connection.html#ssh)

**Comment by Desibabe** [comment]
Thanks for the response. Yes, I am running the same program (itoolkit.js) and I am getting the following error message:

example I used to test: 

node itoolkit.js                                                       

/home/USER/myApp/itoolkit.js:15                                    
    throw error;                                                       
    ^                                                                  
                                                                       
Error: connect ECONNREFUSED 192.168.1.1:22                              
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {  
  errno: 'ECONNREFUSED',                                               
  code: 'ECONNREFUSED',                                                
  syscall: 'connect',                                                  
  address: '192.168.1.1',                                               
  port: 22,                                                            
  level: 'client-socket'                                               
}                                                                      

itoolkit installed:

> yum list installed itoolkit-utils                                                   
  Installed Packages                                                                  
  itoolkit-utils.ppc                         1.0.0-1                          @ibm    
  $                                                                                   
                                                                      

-----Original Message-----

**Comment by ThePrez** [comment]
Since this uses SSH to connect to IBM i, you'll need to make sure the SSH server job is started, via `STRTCPSVR *SSHD`.

That being said, is `192.168.1.1` really the proper IP address of your IBM i system? That's a private IP address often used for Internet gateways, routers, or switches. 
I suspect you really want to connect to `127.0.0.1` instead, since you're running on the IBM i.

**Comment by abmusse** [comment]
@Desibabe Have checked that your SSH server is running like @ThePrez [suggested](https://github.com/IBM/nodejs-itoolkit/issues/285#issuecomment-634709899)?

**Comment by raghunathsmusings** [comment]
This post was really helpful. I also faced the same issue as @Desibabe. I was connecting to my IBMi from a windows 10 machine. Initially I thought that there was some problem in the code. But after following suggestion from @abmusse and installing itoolkit-utils, i was able to successfully run the example.

This thread was super helpful. A hat tip to all contributors!!

**Comment by jdukleth** [comment]
@raghunathsmusings I am getting this same issue running it from Linux and installing the itoolkit-utils on the IBM server didn't help. Did you move the code to the IBM or install something on Windows to get it running from Windows? Thanks.
