### ISSUE TITLE
Handle optional dependencies better

### ISSUE THREAD

**Issue by kadler** [IBM/nodejs-itoolkit#290]
**Is your feature request related to a problem? Please describe.**
Currently, we don't globally import idb-connector, ssh2, or odbc because these are optional dependencies that may not be installed. This is ok, because they are only used by the transports and it's up to the user to use a transport which is installed.

Because of how we do the import, however, the linter flags us for non-global imports and a few other issues. I think we could do this better.

**Describe the solution you'd like**
Instead of doing something like this:
```js
const idbCall = (config, xmlInput, cb) => {
  const {
    dbconn, dbstmt, IN, CLOB, CHAR, SQL_ATTR_DBC_SYS_NAMING, SQL_FALSE,
    // idb-connector is an optional dependency, since users may not use this transport
    // thus we can't globally require it
    // eslint-disable-next-line max-len
    // eslint-disable-next-line global-require, import/no-extraneous-dependencies, import/no-unresolved
  } = require('idb-connector');
```

we could instead wrap the require in a try/catch block:
```js
try {
  let idb = require('idb-connector');
  // TODO: Handle imports of fields somehow
} catch (e) {
  if (e.code !== 'MODULE_NOT_FOUND') {
      throw e;
  }
}
```

https://softwareengineering.stackexchange.com/a/368839
https://stackoverflow.com/a/38885374

**Comment by kadler** [comment]
Hmm, I thought we could get rid of the global-require and no-extraneous-dependencies eslint rules with this, but according [global-require](https://eslint.org/docs/rules/global-require#when-not-to-use-it) doesn't even allow it inside try/catch blocks at the global scope. Also, no-extraneous-dependencies keeps warning me "'package' should be listed in the project's dependencies, not optionalDependencies." even though the [docs](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md#options) say:
> optionalDependencies: If set to false, then the rule will show an error when optionalDependencies are imported. Defaults to true.

**Comment by abmusse** [comment]
Yeah looks like airbnb config forbids optionalDependencies: https://github.com/airbnb/javascript/blob/c5bee75b1b358a3749f1a6d38ee6fad73de28e29/packages/eslint-config-airbnb-base/rules/imports.js#L95

So we need to tweak the rules by adding 

```
"import/no-extraneous-dependencies": [ "error", { "optionalDependencies": true }]
```

To [.eslint.js](https://github.com/IBM/nodejs-itoolkit/blob/master/.eslintrc.js#L12) to resolve this issue.
