### ISSUE TITLE
iWork returns invalid character error while using '<' and '&'

### ISSUE THREAD

**Issue by epligrow** [IBM/nodejs-itoolkit#309]
* **Node.js version**: v12.18.3
* **itoolkit version**: 1.0.0
* **IBM i version**: 7.3
* **XMLSERVICE version**: 1.9.9.3

**Describe the bug**
The iWork.getDataArea function throws an "Invalid character" error when the data area contains "<" or "&".
{
  Unencoded <
  Line: 9
  Column: 66
  Char: -
}

**To Reproduce**
1. Create Connection object
2. Create iWork object
3. Run iWork.getDataArea() on a data area containing an "&" or a "<".

**Expected behavior**
Return data area contents.

**Comment by kadler** [comment]
@abmusse There is an XMLSERVICE control option `*cdata` that wraps data returned in cdata tags. This is indiscriminate, though, so Mo Ji added code to escape reserved tokens which is in some 2.0.1 version (the change didn't get a version number, unfortunately).

@epligrow "3.1.4-340.x86_64" is certainly not an IBM i version. If you let me know what IBM i release you are on, I can give you the PTF number.

**Comment by epligrow** [comment]
@kadler That would explain why the number is not correct. The real number is 7.3. I'm going to update the main issue as well.

**Comment by kadler** [comment]
For 7.3, the latest PTF is SI70668.

**Comment by epligrow** [comment]
I checked on this after installing that PTF and got the same error. Here is a picture of the XML data and the error generated.
![image](https://user-images.githubusercontent.com/38891205/91095824-974e7780-e622-11ea-959f-189101c65da1.png)
![image](https://user-images.githubusercontent.com/38891205/91095894-b3521900-e622-11ea-861b-12c2b1ffe188.png)

**Comment by kadler** [comment]
Hmm. You could try to enable the CDATA option by specifying `ctl: '*here *cdata'` in your connection options.

**Comment by abmusse** [comment]
```js
const connection = new Connection({
  transport: 'odbc',
  transportOptions: { ... , ctl: '*here *cdata'}
});

```

**Comment by epligrow** [comment]
That seemed to do it. I tried running the statement with both symbols and they both ran without a hitch. Thanks for your help!
