### ISSUE TITLE
Can DB2 transport method handle 300 to 500 requests at any given instance ? 

### ISSUE THREAD

**Issue by RudraRudra123** [IBM/nodejs-itoolkit#313]
Hello, We are building a Node.js application running on PASE environment of IBMi system interacting with backend RPG programs through DB2 stored procedure transport method. This Node.js application serving requests from Web user interface built using React.js. For any given instance, we may receive around 300-500 requests hence I would like to know the factors influencing the response time of itoolkit.  Also suggest whether Rest (Apache-HTTP server) transport is best suited in my case ? Appreciate your help!

**Comment by ThePrez** [comment]
Greetings. The throughput performance is a difficult question to answer, and it depends on many things. You should be able to handle large volumes of requests, but you will likely need to do a few rounds of tweaking and analysis (for instance, reusing the connection objects within your application when possible). Quite often, with an architecture like this, the largest source of contention comes on the RPG/database side (with expensive lock algorithms and things like that having an influence), but it all depends on application design. 

A popular approach is to expose those backend RPG programs through SQL (through use of stored procedures, UDFs, or UDTFs), and then getting at that business logic through database calls (for which you'd use `idb-connector`, `idb-pconnector`, or `odbc` directly). This helps provide a layer of language-agnosticism as well as connection flexibility, but it also provides you with more insights into what queries are impacting performance in the SQL Performance Center tools.
