### ISSUE TITLE
Change documentation to recommend a different XML parser

### ISSUE THREAD

**Issue by xWyatt** [IBM/nodejs-itoolkit#344]
**Is your feature request related to a problem? Please describe.**
The migration guide and README implicitly recommend using `xml2js` to parse XML output from itoolkit. `xml2js` doesn't appear to be [actively maintained](https://github.com/Leonidas-from-XIV/node-xml2js/issues/626) and has issues with [parsing blank values from non-named keys](https://github.com/Leonidas-from-XIV/node-xml2js/issues/463) which we have found to be an issue when getting returned values out of an RPG DS.

**Describe the solution you'd like**
I'd like to open a PR to change the docs to recommend a different XML parser. We have found [fast-xml-parser](https://www.npmjs.com/package/fast-xml-parser) to work quite well in lieu of `xml2js` and, in my opinion, the output JSON object is much cleaner (see below for screenshots).

**Additional context**
From `xml2js`, example output from an RPG DS with a `7s0` type with a `0` value. Note `charkey` `_` exists in this object:
![image](https://user-images.githubusercontent.com/3946540/179094763-b5429904-e090-42e1-85cc-da86e89a869c.png)

Also from `xml2js`, example output from an RPG DS with a `15a` type and a `""` value. Note `charkey` `_` does _not_ exist. This is inconsistent behavior:
![image](https://user-images.githubusercontent.com/3946540/179095138-92fdf7ba-28a8-4b5b-bcf6-633d3803356e.png)

From `fast-xml-parser`, the same `15a` returns a blank value - this is what I expect:
![image](https://user-images.githubusercontent.com/3946540/179095365-87c4e985-d8bf-4ab4-b631-ec82fe5fb6e2.png)

**Comment by kadler** [comment]
Sounds good to me.

**Comment by abmusse** [comment]
I agree since its not really being maintained we should probably recommend a different parser.

Making a note here that we use xml2js in:
- tests
- internal calls in [Deprecated.js](https://github.com/IBM/nodejs-itoolkit/blob/c4f5e2952cd4eced07f940e704e609008eed15a7/lib/Deprecated.js#L28)
- docs

**Comment by alanseiden** [comment]
Should we begin by making pull requests to update the code examples (e.g. pages like this one: https://nodejs-itoolkit.readthedocs.io/en/latest/ProgramCall.html#examples), replacing xml2js with the equivalent usage of fast-xml-parser?

**Comment by alanseiden** [comment]
The iToolkit package.json file includes xml2js as a dependency: https://github.com/IBM/nodejs-itoolkit/blob/c4f5e2952cd4eced07f940e704e609008eed15a7/package.json#L44
I suppose we'd have to make a PR to update that to fast-xml-parser as well.

**Comment by abmusse** [comment]
`xml2js` is still used in internal calls in [Deprecated.js](https://github.com/IBM/nodejs-itoolkit/blob/c4f5e2952cd4eced07f940e704e609008eed15a7/lib/Deprecated.js#L28).
We cannot remove xml2js as a dependency until its replaced in all the internal calls. 
We also use xml2js in tests. 

@ThePrez @kadler Thoughts on gutting xml2js everywhere?

**Comment by abmusse** [comment]
> Should we begin by making pull requests to update the code examples (e.g. pages like this one: https://nodejs-itoolkit.readthedocs.io/en/latest/ProgramCall.html#examples), replacing xml2js with the equivalent usage of fast-xml-parser?

I believe @xWyatt Updated the code examples in this [PR](https://github.com/IBM/nodejs-itoolkit/pull/345/files#diff-3f0518fc9962959aaba7aab4c9be37d822bdda60ec5d3cb9953ef803af1a2f3cR2)

**Comment by alanseiden** [comment]
> `xml2js` is still used in internal calls in [Deprecated.js](https://github.com/IBM/nodejs-itoolkit/blob/c4f5e2952cd4eced07f940e704e609008eed15a7/lib/Deprecated.js#L28). We cannot remove xml2js as a dependency until its replaced in all the internal calls. We also use xml2js in tests.
> 
> @ThePrez @kadler Thoughts on gutting xml2js everywhere?

I was thinking to keep `xml2js` as a dependency while it's needed internally, but add `fast-xml-parser` to permit upgrading to the new component where needed.

**Comment by abmusse** [comment]
> > `xml2js` is still used in internal calls in [Deprecated.js](https://github.com/IBM/nodejs-itoolkit/blob/c4f5e2952cd4eced07f940e704e609008eed15a7/lib/Deprecated.js#L28). We cannot remove xml2js as a dependency until its replaced in all the internal calls. We also use xml2js in tests.
> > @ThePrez @kadler Thoughts on gutting xml2js everywhere?
> 
> I was thinking to keep `xml2js` as a dependency while it's needed internally, but add `fast-xml-parser` to permit upgrading to the new component where needed.

Yes adding `fast-xml-parser` as a dependency would be good.

**Comment by kadler** [comment]
> @ThePrez @kadler Thoughts on gutting xml2js everywhere?

Sounds great to me. I think we wanted to do that initially but due to lack of time, we left it for the internal stuff.

**Comment by abmusse** [comment]
> internal

OK I will make an issue for this and tackle it in a follow-up PR
