### ISSUE TITLE
service program parameter pass by value

### ISSUE THREAD

**Issue by jkdavew** [IBM/nodejs-itoolkit#35]
XMLSERVICE 1.9.9.3 (03–13–2017) reported a fix for by="val" to be on <param>, not <data> but it looks like itoolkit is still passing it on the <data> tag.  This is a problem when using itoolkit with a procedure containing a parameter passed by value in a service program.

**Comment by abmusse** [comment]
PR #36

**Comment by jkdavew** [comment]
Abdirahim,

I went to sign and notice the signature was wrong.  I got a new laptop and
did the sign before realizing it wasn't linked to my Github account.
Because of that my signature was wrong.  I tried several other attempts but
nothing seemed to work.  I also tried to rebase with no luck.  Ideally I
want to undo all of my commit this morning and start over!  I'd imagine
you're much more familiar with Git and could use your guidance.

Thanks,
Dave

**Comment by kadler** [comment]
@jkdavew you can use `git rebase -i` to rebase the commits. You need to pass a parent commit (the one before your commits). Then you can change the "pick" to "reword" or "r" to edit the commit message for each of those commits. Add or edit the "Signed-off-by" tag in the commit message for each one. Once that's done, you can `git push --force` to replace the PR commits with the new commits.

Here's a good article about doing this: https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history

If you get stuck, feel free to ask for more help.

**Comment by abmusse** [comment]
@jkdavew 

> Ideally I want to undo all of my commit this morning and start over!

Using `git rebase -i` as mentioned by @kadler you can drop unwanted commits by changing "pick" to "drop". 

That way you can remove the unwanted commits.

**Comment by kadler** [comment]
Using `git reset` will be easier. I documented it over on the PR: https://github.com/IBM/nodejs-itoolkit/pull/36#issuecomment-468372456

**Comment by jkdavew** [comment]
I see this has been approved & merged, but it's not yet in NPM.  Curious what the migration plan is for that environment.  Also - should I be deleting my forked repo (seen some mixed information regarding best practice).

**Comment by kadler** [comment]
The usual cleanup duties are to delete the branch you submitted the PR from, but in this case I see that you did it from your master branch, so in that case you would not do that. (Note: The usual best practice is to always create a branch before making changes).

As to cleaning up the repo, you can do that if you like or leave it to rot (there's a lot of rotting forks on GitHub). GitHub recently added a feature to do this once your PR is closed: https://github.com/isaacs/github/issues/673#issuecomment-463879985, though it may be in beta or something as I haven't seen any blog post advertising it. Otherwise, you can follow the guide here: https://help.github.com/en/articles/deleting-a-repository

**Comment by jkdavew** [comment]
I think I originally did it from master, but then from a branch instead.
 For now I'll just leave it alone.... Maybe when the pr gets closer it will
do some cleanup as you mentioned.

What about the npm module... Does the get updated separately from your team?

**Comment by abmusse** [comment]
@dmabupt 

Can we release a new version `0.1.7`?

@jkdavew PR #43 was merged into master.

**Comment by abmusse** [comment]
@jkdavew 

https://www.npmjs.com/package/itoolkit/v/1.0.0-alpha.0

This release includes the changes from your PR.

`npm install itoolkit@alpha`

**Comment by jkdavew** [comment]
Great thank you!
