### ISSUE TITLE
Upgrade minimum node engine?

### ISSUE THREAD

**Issue by abmusse** [IBM/nodejs-itoolkit#354]
Currently we say minimum node 8. Which is way outdated now

https://github.com/IBM/nodejs-itoolkit/blob/265f4c54a05937d7f12fc7b1c1f157de23ff79b4/package.json#L62

**Comment by markdirish** [comment]
I don't think there's anything this package does that couldn't be node 8, but there are no guarantees for our dependencies. https://endoflife.date/nodejs says that Node.js 14, 16, and 18 are the current "support triad", so I guess 14 would make sense?

**Comment by abmusse** [comment]
No need to change this at the moment
