### ISSUE TITLE
NEW CASE FOR IBMi : *CURRENT for user profile and password is not accepted .

### ISSUE THREAD

**Issue by KobiSaada** [IBM/nodejs-itoolkit#388]
* **Node.js version**:
* **itoolkit version**:
* **IBM i version**:
* **XMLSERVICE version**:

**Describe the bug**
To clear things out: we are not trying to change the user profile and password, we are trying to connect to IBM i via NodeJS running on the IBM i.

Connection procedure as described in the  documentation of XMLSERVICES using *CURRENT in username and password. This does not work. If instead we specify an IBM i user and password it works.

**Screenshots**
const { Connection} = require('itoolkit'); //xml services
 const connection = new Connection({
    transport: 'ssh',
    transportOptions: {
      database: '*LOCAL',
      username: *CURRENT,
      password: *CURRENT,
      host: 'localhost',
    },
  });

and its not connected even im already connected to the system and even i run it from the ibmi/as400 system.

I would appreciate a solution, thanks.

**Comment by kadler** [comment]
The IBM i Access ODBC driver has a limitation that using *CURRENT does not work if the user has PASSWORD(*NONE). Does the user have a password assigned?

**Comment by KobiSaada** [comment]
Yes the user have a password

בתאריך יום ב׳, 18 במרץ 2024 ב-17:18 מאת Kevin Adler <
***@***.***>:

**Comment by kadler** [comment]
Oh I missed that you were using SSH, yeah you need to provide a username and password in that case or use an SSH key. See the examples: https://nodejs-itoolkit.readthedocs.io/en/latest/Connection.html#examples

**Comment by KobiSaada** [comment]
There is any way to use *CURRENT for user and password in nodejs
-toolkit-xmlservices?

בתאריך יום ג׳, 19 במרץ 2024 ב-15:49 מאת Kevin Adler <
***@***.***>:

**Comment by abmusse** [comment]
`*CURRENT` is a special odbc feature. The SSH transport requires passing the password or using key authentication.

Please see the using key based authentication if you don't want to use a password with SSH transport: https://nodejs-itoolkit.readthedocs.io/en/latest/Connection.html#examples
