### ISSUE TITLE
AS400 - RPG Debug option when triggered from Node.js

### ISSUE THREAD

**Issue by sridhar7290** [IBM/nodejs-itoolkit#39]
Hi All

I would like to know if there is anyway to debug AS400 programs when called from Node.Js applications.
As it is a stateless i'm unable to capture the Job Details to do a service job and debug.

Thanks in advance
Sri

**Comment by kadler** [comment]
If you are using the database transport, you should be able to use the special `*LOCAL-*DEBUG` database name to put the database job in to a MSGW. There's an example of doing this here: http://yips.idevcloud.com/wiki/index.php/Databases/DB2Debug

**Comment by sridhar7290** [comment]
Thank you  Kevin.

It worked well while it is a DB2 Job process.. (Transport is Db2)
If in case, i use REST Process, could you help me with options to invoke a debug.
Thanks in advance

**Comment by sridhar7290** [comment]
Was able to figure out the solution
When using REST
let option = {
    host: "<ip>",
    port: portnumber,
    path: "/cgi-bin/xmlcgi.pgm",
    ctl : "*here *debug",
    buffer: 500000,
};
and connection to be : 
let conn = new xt.iConn('*LOCAL', '<USERID>', '<PWD>',option);

After executing in IBM iseries 
1. We get a Message in QSYSOPR (DSPMSG QSYSOPR) as 
Debug client 147345/QUSER/QSQSRVR
2. Take 5 to open the message then F9 to find the Job details
3. Work job on the Job details to find : 

_Job 147345/QUSER/QSQSRVR started on 03/01/19 at 05:08:58 in subsystem
  QSYSWRK in QSYS. Job entered system on 03/01/19 at 05:08:58.       
Printer device PRT01 not found.                                      
Job changed successfully; however errors occurred.                   
User Profile = SVARAHA                                               
SERVER MODE CONNECTING JOB IS 738900/QTMHHTTP/NODESRV.               
Debug client 147345/QUSER/QSQSRVR_                                    

4. STRSRVJOB on 147345/QUSER/QSQSRVR_                                    
5. STRDBG <your Pgm> 
6. Give G as reply to the message in QSYSOPR
7. Your job is in Debug.
8. ENDDBG and ENDSRVJOB after debug completion.
