### ISSUE TITLE
Simplify/remove ixml.js

### ISSUE THREAD

**Issue by kadler** [IBM/nodejs-itoolkit#46]
ixml.js includes various definitions for XMLSERVICE tags and attributes. This is way overly complicated and over-engineered. 

For instance, `I_XML_ATTR_KEY_ERROR` is defined to the string "error". Having definitions like this _can_ be useful, however:

- this string will *never* change as it would break compatibility
- "error" is _in_ the key name, so you already have to know what you're looking for
- `I_XML_ATTR_KEY_ERROR` is longer and more complicated to type (caps, underscores)

This abstraction brings *no benefits* whatsoever, while imposing extra mental effort to understand and parse the abstraction.

A better model would be to use Javascript template literals or possibly a template engine (though this might be overkill as well).

**Comment by markdirish** [comment]
I think when we start removing these constants, and using the literals strings in the templates for the nodes, we will see that there are only a few dozen 'node templates' with a few options for each that need to be accounted for.  Also the fact they they are all declared, and _then_ all exported makes the file a lot larger than it will eventually end up.

I think native template literals are a great idea, and should probably be the starting point until we find a deficiency.
