### ISSUE TITLE
Proposal for factory class

### ISSUE THREAD

**Issue by ThePrez** [IBM/nodejs-itoolkit#48]
I'd like to propose a new factory method (either in this module or a closely-related module, like `itoolkit-factory`). 

The idea is that an application can run on any platform (Linux, IBM i, Mac, Cloud) and not need to worry about choosing the correct transport. Instead, the factory should select the best transport for the surrounding operating environment. This would allow applications to be able to developed or deployed anywhere without code changes (and without understanding the various transports)

The factory would take in (`hostname`) as a constructor and have (`username`, `password`) as parameters. Proposed logic would be, in pseudocode:
```pascal
if ( `idb-pconnector` is installed and ibmi ) 
   try returning a toolkit object with `idb-pconnector` transport
if ( `idb-connector` is installed and ibmi ) 
   try returning a toolkit object with `idb-connector` transport
if ( `odbc` is installed) 
   try returning a toolkit object with `odbc` transport
if ( `ssh2` is installed) 
   try returning a toolkit object with `ssh2` transport
else
   try returning a toolkit object with REST transport (perhaps check an env var or have an extra param for port number)
```
The factory will also need to be able to clean up connections. 
The factory could also manage connections itself so that every request doesn't get a new instance of the transport mechanism (for instance, using a single SSH connection for all the requests, or using connection pooling)

**Comment by kadler** [comment]
I'm not sure this is a good idea. A lot of things could go wrong with this "magic" code.

**Comment by kadler** [comment]
The itoolkit constructor already takes an object that takes in configuration for your transport in a _declarative_ way without requiring code, thus they can just define a configuration file without having to change their code.
