### ISSUE TITLE
Document constructor attributes

### ISSUE THREAD

**Issue by kadler** [IBM/nodejs-itoolkit#55]
AFAICT, [returnError](https://github.com/IBM/nodejs-itoolkit/blob/v1.0-dev/lib/Connection.js#L53) is not documented in the README.

**Comment by kadler** [comment]
https://github.com/IBM/nodejs-itoolkit/tree/v1.0-dev#connection needs a function signature and needs to describe how it behaves with the old parameters and the new object constructor as well as a list of object attributes that are supported by the constructor. Something like https://serialport.io/docs/api-stream#constructor

**Comment by abmusse** [comment]
@kadler 

I'm working on this as part of the overall #10 and #22 goals

**Comment by abmusse** [comment]
I'm planning on creating docs/README.md which will document the API.

**Comment by abmusse** [comment]
Closing after merging PR #58
