### ISSUE TITLE
Bug in translating XML to JSON - error markup

### ISSUE THREAD

**Issue by kganczuk** [IBM/nodejs-itoolkit#62]
There is a bug during translating XML to JSON.
itoolkit.js, errorReg constant.
In XML there is a new line sign between <error> markups, I got nulls instead of error code.
Adding new line sign resolves this problem.

Suggesting change this line of code: 
`  const errorReg = /<error>.*?\*\*\* error (.*?)<\/error>.*?<error>(.*?)<\/error>/;`
To this:
`  const errorReg = /<error>.*?\*\*\* error (.*?)<\/error>.*?\n<error>(.*?)<\/error>/;`

**Comment by abmusse** [comment]
There a few issues open related to `xmlToJson` we are currently exploring using `xml2js` and deprecate using xmlToJson.

Check out PR #53

**Comment by kadler** [comment]
We have no plans to enhance or fix XmlToJson and instead plan to drop it in the future. We suggest you use [xml2js](https://www.npmjs.com/package/xml2js) instead.
