### ISSUE TITLE
Documentation needs new home

### ISSUE THREAD

**Issue by ThePrez** [IBM/nodejs-itoolkit#87]
Current link points to https://www.ibm.com/developerworks/community/wikis/home?lang=en#!/wiki/IBM%20i%20Technology%20Updates/page/Toolkit%20for%20i%20APIs

There is a TODO in the readme about this, but I figure it's better to track in an issue.

**Comment by abmusse** [comment]
@ThePrez 

One we release v1.0.0 can we simply update developer works to point to our [docs](https://github.com/IBM/nodejs-itoolkit/blob/master/docs/README.md) folder?

**Comment by ThePrez** [comment]
No. The developerWorks site is going away. But we can just have the npm module point to the right spot

**Comment by ThePrez** [comment]
I see that is already done for v1.x, so nothing needs to be done unless v1 is still alpha when developerWorks goes away

**Comment by kadler** [comment]
@abmusse and I think the best solution is using [mkdocs](https://www.mkdocs.org/) in conjunction with https://readthedocs.org.

**Comment by abmusse** [comment]
@kadler 

For v1.0.0 lets maintain the docs within the repository [docs](https://github.com/IBM/nodejs-itoolkit/blob/master/docs/README.md) folder.

We can use mkdocs in conjunction with https://readthedocs.org. at a later time.
