### ISSUE TITLE
Adding data structure name to the XMLtoJSON-converter

### ISSUE THREAD

**Issue by abmusse** [IBM/nodejs-itoolkit#9]
**[Original report](https://bitbucket.org/litmis/nodejs-itoolkit/issue/9) by Torbjørn Høivik (Bitbucket: [torban91](https://bitbucket.org/torban91), GitHub: Unknown).**

----------------------------------------

Hey, we've been using the itoolkit for a little while and noticed the XMLtoJSON-converter cuts away the datastructure name from the XML.

Example:

XML response:

```
#!XML

<?xml version='1.0'?><myscript><pgm name='SKSFOR03' error='fast'>
<parm io='META'>
<ds len='1'>
<data type='256A'></data>
<data type='50A'>FTJ01</data>
<data type='5A'>00000</data>
<data type='15A'>INFO</data>
<data type='100A'>Processing ok (00000)</data>
<data type='10A'>2017-09-14</data>
<data type='8A'>09.50.15</data>
<data type='12A'>000000000000</data></ds>
</parm><parm io='FORINN'>
<ds len='1'><data type='11A'>2346</data></ds>
</parm><parm io='FORUTMETA'>
<ds len='1'>
<data type='5A'>7</data>
<data type='11A'>400509401</data></ds></parm>
<parm io='FORUT'>
<ds dim='140' len='1'>
<data type='11A'>15365409</data>
<data type='5A'>4</data>
<data type='3A'>M07</data>
<data type='30A'>Bilforsikring (ansatt)</data>
<data type='75A'>HONDA , 2016, ZA17792, 75% bonus 1.Ã¥r, -> 75% bonus 2.Ã¥r</data><data type='1A'>A</data>
<data type='8A'>20170525</data>
<data type='8A'>20180525</data>
<data type='10A'>NICE_SP1G</data>
<data type='5A'>AUTO</data>
<data type='1A'>Y</data>
<data type='11A'>70</data>
<data type='25A'>SpareBank 1 Skadeforsikri</data><data type='50A'>HONDA</data><data type='10A'>10</data>
<data type='10A'>ZA17792</data>
<data type='1A'>N</data><data type='1A'>Y</data>
<data type='1A'>Y</data><data type='1A'>N</data>
<data type='1A'>N</data><data type='1A'>J</data>
<data type='1A'></data></ds>
<ds dim='140' len='1'><data type='11A'>10700169</data><data type='5A'>13</data><data type= ...
...
...
...
..
```

After we've converted it to JSON:

```
#!JSON
{
    "type": "pgm",
    "success": true,
    "data": [
        {
            "type": "256A",
            "value": ""
        },
        {
            "type": "50A",
            "value": "FTJ01"
        },
        {
            "type": "5A",
            "value": "00000"
        },
        {
            "type": "15A",
            "value": "INFO"
        },
        {
            "type": "100A",
            "value": "Processing ok (00000)"
        },
        {
            "type": "10A",
            "value": "2017-09-27"
        },
        {
            "type": "8A",
            "value": "10.26.18"
        },
        {
            "type": "12A",
            "value": "000000000000"
        },
        {
            "type": "11A",
            "value": "2346"
        },
        {
            "type": "5A",
            "value": "7"
        },
        {
            "type": "11A",
            "value": "400509401"
        },
        {
            "type": "11A",
            "value": "15365409"
        },
        {
            "type": "5A",
            "value": "4"
        },
        {
            "type": "3A",
            "value": "M07"
        },
        {
            "type": "30A",
            "value": "Bilforsikring (ansatt)"
        },
        {
            "type": "75A",
            "value": "HONDA , 2016, ZA17792, 75% bonus 1.år, -> 75% bonus 2.år"
        },
        {
            "type": "1A",
            "value": "A"
        },
        {
            "type": "8A",
            "value": "20170525"
        },
        {
            "type": "8A",
            "value": "20180525"
        },
        {
            "type": "10A",
            "value": "NICE_SP1G"
        },
        {
            "type": "5A",
            "value": "AUTO"
        },
        {
            "type": "1A",
            "value": "Y"
        },
        {
            "type": "11A",
            "value": "70"
        },
        {
            "type": "25A",
            "value": "SpareBank 1 Skadeforsikri"
        },
        {
            "type": "50A",
            "value": "HONDA"
        },
        {
            "type": "10A",
            "value": "10"
        },
        {
            "type": "10A",
            "value": "ZA17792"
        },
        {
            "type": "1A",
            "value": "N"
        },
        {
            "type": "1A",
            "value": "Y"
        },
        {
            "type": "1A",
            "value": "Y"
        },
        {
            "type": "1A",
            "value": "N"
        },
        {
            "type": "1A",
            "value": "N"
        },
        {
            "type": "1A",
            "value": "J"
        },
        {
            "type": "1A",
            "value": ""
        },
        {
            "type": "11A",
            "value": "10700169"
        },
        {
            "type": "5A",
            "value": "13"
        },
        {
            "type": "3A",
            "value": "M07"
        },
        {
            "type": "30A",
            "value": "Bilforsikring (ansatt)"
        },
        ...
       ...
...
}
```

We would very much like to keep the <parm io='META'> etc. tags in the json-response so we can see where the data belongs. This becomes especially true with the 'FORUT'-tag as this can have several items in it's response and makes it difficult to seperate out which data belongs to which item.

**Comment by karanlamba** [comment]
Hi, we have been testing with toolkit and encountered this same issue with XMLtoJSON when outputting arrays(dims). I’ve noticed this issue is quite old, are there still plans to modify this function? We are considering our options to use different xml to json converter or modifying xmltojson but felt it would be prudent to reach out and get current status of this issue first.

**Comment by abmusse** [comment]
Hello @karanlamba 

Thanks for reaching out! 

Tony's comments above sums up the issues nicely.

> Correct. This converter XMLtoJSON is faulty. That is, XMLSERVICE will send back complete data structures and records (assuming input correct), but XMLtoJSON will 'data reduce' many things out of existence. This is one of the Achilles heels of this itoolkit.

> What to do? Well, XMLtoJSON needs to be completely restructured. I really don't have the time, so volunteers would be welcome.

We have also considered using an XML parser instead of `xmlToJson`.

We will either need to rework `xmlToJson` or replace it with a third party XML parser something like [xml2js](https://www.npmjs.com/package/xml2js). The cavet with going with third party parser it may not work well with the quirks of XMLSERVICE. 

This [issue] is also points a false positive from `xmlToJson`.


Hey @kadler @ThePrez @markdirish @dmabupt ,  what are your thoughts on resolving `xmlToJson` issues?

**Comment by jkdavew** [comment]
following

**Comment by ThePrez** [comment]
The xmlToJson() converter undoubtedly needs fixing (and I think we're all in agreement on that). 

@jkdavew / @karanlamba, I assume you are both running into immediate problems. I'm guessing the quickest "fix" is to use something like xml2js directly in your application. Please try that and verify that it  works (and what your specific solution looked like). 

This issue has sat dormant for a very long time, but thanks to the pings, the itoolkit team is now thinking about this issue again. We'll investigate solutions, but also welcome any level of collaboration. I don't think a quick resolution exists that doesn't introduce a lot of risk, so we need to proceed very deliberately.

If someone starts developing a new implementation, I'd suggest a [draft PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/), which will allow us to view and discuss the changes before marking them as a contribution candidate.

**Comment by kadler** [comment]
We have no plans to improve XmlToJson, but instead intend to drop it in the future. We suggest moving to [xml2js](https://www.npmjs.com/package/xml2js) instead as @ThePrez suggested.
