### ISSUE TITLE
Update docs to reflect V1 changes

### ISSUE THREAD

**Issue by kadler** [IBM/nodejs-itoolkit#95]

**Comment by abmusse** [comment]
Currently our main README includes a [TODO](https://github.com/IBM/nodejs-itoolkit#odbc) to add installation instructions for the ODBC transport.

We can add a link in the README to to the our odbc setup guide https://github.com/IBM/ibmi-oss-examples/blob/master/odbc/odbc.md#table-of-contents

**Comment by abmusse** [comment]
Need to update [ProgramCall.addParam](https://github.com/IBM/nodejs-itoolkit/blob/master/lib/ProgramCall.js#L75) docs after #139 was merged.
