### ISSUE TITLE
Deprecate xmlTojson

### ISSUE THREAD

**Issue by kadler** [IBM/nodejs-itoolkit#99]
This will be removed in v2.

Need to update replace references to xml2json with xml2js in:
- [x] docs
- [x] examples
- [x] tests
- [x] code

**Comment by kadler** [comment]
@abmusse with #160 merged, is this complete?

**Comment by abmusse** [comment]
Yes mostly complete aside from 2 small issues

- lingering xmlToJson import in [Toolkit.js](https://github.com/IBM/nodejs-itoolkit/blob/master/lib/Toolkit.js#L20).
- we should log a deprecation warning when xmlToJson is used.

**Comment by abmusse** [comment]
Should we also move xmlToJson to Deprecated.js?
